bin.includes = META-INF/,\
               .,\
               lib/,\
               lib/cics-java-jcics-tdq-record-1.0.jar
source.. = src/main/java/
jre.compilation.profile = JavaSE-17
jars.compile.order = .,\
                     lib/cics-java-jcics-tdq-record-1.0.jar
